/**
* DNS API
* ## Working with the API Every endpoint uses the `X-API-Key` header for authorization, to obtain the key please see the [Official Documentation](/docs/getstarted).  Please note that any zone or record updates might conflict with active services. In such cases, the DNS records belonging to the conflicting services will be deactivated.  ## Support Support questions may be posted in English: <a href='/docs/getstarted#support'>API Beta Support</a>.  Please note that in the Beta phase we offer support in the business Hours Mo-Fri 9:00-17:00 EET. <h2> <details>   <summary>Release notes</summary>    Vesion 1.0.0   Exposed CRUD operations for customer zone. </details> </h2> 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Record
import org.openapitools.client.models.ZoneTypes

import com.squareup.moshi.Json

/**
 * 
 * @param id The zone id.
 * @param name The zone name
 * @param type 
 * @param records 
 */

data class CustomerMinusZone (
    /* The zone id. */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* The zone name */
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "type")
    val type: ZoneTypes? = null,
    @Json(name = "records")
    val records: kotlin.collections.List<Record>? = null
)

