/**
* DNS API
* ## Working with the API Every endpoint uses the `X-API-Key` header for authorization, to obtain the key please see the [Official Documentation](/docs/getstarted).  Please note that any zone or record updates might conflict with active services. In such cases, the DNS records belonging to the conflicting services will be deactivated.  ## Support Support questions may be posted in English: <a href='/docs/getstarted#support'>API Beta Support</a>.  Please note that in the Beta phase we offer support in the business Hours Mo-Fri 9:00-17:00 EET. <h2> <details>   <summary>Release notes</summary>    Vesion 1.0.0   Exposed CRUD operations for customer zone. </details> </h2> 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* Holds supported dns record types.
* Values: a,aAAA,cNAME,mX,nS,sOA,sRV,tXT,cAA
*/

enum class RecordTypes(val value: kotlin.String) {


    @Json(name = "A")
    a("A"),

    @Json(name = "AAAA")
    aAAA("AAAA"),

    @Json(name = "CNAME")
    cNAME("CNAME"),

    @Json(name = "MX")
    mX("MX"),

    @Json(name = "NS")
    nS("NS"),

    @Json(name = "SOA")
    sOA("SOA"),

    @Json(name = "SRV")
    sRV("SRV"),

    @Json(name = "TXT")
    tXT("TXT"),

    @Json(name = "CAA")
    cAA("CAA");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

